# Generated by Django 3.1.4 on 2021-08-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('song', models.FileField(upload_to='songs')),
            ],
        ),
    ]
